"""Canonical enums encoded verbatim from Appendix B (WS1-02)."""
from enum import Enum


class MovementType(Enum):          # B.1
    PAYIN = "PAYIN"; FEE = "FEE"
    CONVERSION_SELL = "CONVERSION_SELL"; CONVERSION_BUY = "CONVERSION_BUY"
    PAYOUT = "PAYOUT"; SETTLEMENT = "SETTLEMENT"
    RETURN = "RETURN"; REFUND = "REFUND"; REVERSAL = "REVERSAL"
    ADJUSTMENT = "ADJUSTMENT"
    PREFUND_DRAWDOWN = "PREFUND_DRAWDOWN"; PREFUND_TOPUP = "PREFUND_TOPUP"


class TransferStatus(Enum):        # B.2
    SUBMITTED = "SUBMITTED"; FUNDS_RECEIVED = "FUNDS_RECEIVED"; PROCESSING = "PROCESSING"
    PAYOUT_INITIATED = "PAYOUT_INITIATED"; COMPLETED = "COMPLETED"
    ON_HOLD = "ON_HOLD"; RETURNED = "RETURNED"; REFUNDED = "REFUNDED"
    FAILED = "FAILED"; CANCELLED = "CANCELLED"


class LegStatus(Enum):             # B.3
    CREATED = "CREATED"; PENDING = "PENDING"; IN_FLIGHT = "IN_FLIGHT"
    CONFIRMED = "CONFIRMED"; SETTLED = "SETTLED"
    RETURNED = "RETURNED"; FAILED = "FAILED"; REVERSED = "REVERSED"


class LegKind(Enum):
    PAYIN = "PAYIN"; CONVERSION = "CONVERSION"; PAYOUT = "PAYOUT"


class PaymentStatus(Enum):         # B.4 normalized provider status
    PENDING_SUBMISSION = "PENDING_SUBMISSION"; SUBMITTED = "SUBMITTED"; ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"; CONFIRMED = "CONFIRMED"; REJECTED = "REJECTED"
    RETURNED = "RETURNED"; FAILED = "FAILED"; CANCELLED = "CANCELLED"; UNKNOWN = "UNKNOWN"


class RefundFamily(Enum):          # B.5 (distinct families)
    RETURN = "RETURN"; REFUND = "REFUND"; RECALL = "RECALL"; REVERSAL = "REVERSAL"


class PartnerRole(Enum):           # B.6
    PAYIN = "PAYIN"; PAYOUT = "PAYOUT"; FX = "FX"; NOSTRO = "NOSTRO"


class BalanceType(Enum):           # B.7
    LEDGER = "LEDGER"; RESERVED = "RESERVED"; AVAILABLE = "AVAILABLE"
    CLEARED = "CLEARED"; EXPECTED = "EXPECTED"; PREFUND_AVAILABLE = "PREFUND_AVAILABLE"


class Direction(Enum):
    DEBIT = "DEBIT"; CREDIT = "CREDIT"
